import { test, expect } from "@playwright/test";

test("admin permissions, denied retrieval, granted chart and architecture", async ({ page }) => {
  test.setTimeout(120000);
  const errors: string[] = [];
  page.on("pageerror", e => errors.push(e.message));
  const status = await page.request.get("/api/auth/status");
  const setup = (await status.json()).setup_required;
  // Exercise first-run setup through the UI on a fresh isolated server.
  await page.goto("/");
  if (setup) await page.getByLabel("Workspace ID").fill("acme");
  await page.getByLabel("Email address").fill("admin@example.test");
  await page.getByLabel("Password", { exact: true }).fill("test-workspace-password");
  await page.getByRole("button", { name: setup ? "Create workspace" : "Sign in", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Your documents. Only your answers." })).toBeVisible();
  await page.screenshot({ path: "../.scratch/zero-trust-ask.png" });
  await page.getByRole("button", { name: "People & access", exact: true }).click();
  await page.getByLabel("Email address").fill("alice@example.test");
  await page.getByLabel("Initial password").fill("test-workspace-password");
  await page.getByRole("combobox", { name: "Role", exact: true }).selectOption("employee");
  await page.getByRole("button", { name: "Create account", exact: true }).click();
  await expect(page.locator(".people-list")).toContainText("alice@example.test");
  await page.getByRole("button", { name: "Ask your documents", exact: true }).click();
  await page.locator(".upload-button").click();
  await expect(page.getByRole("heading", { name: "Upload with permissions" })).toBeVisible();
  await page.getByLabel("Classification").selectOption("confidential");
  await page.getByLabel("finance", { exact: true }).check();
  const chooser = page.waitForEvent("filechooser");
  await page.getByRole("button", { name: "Choose files & upload" }).click();
  await (await chooser).setFiles({ name: "private-finance.md", mimeType: "text/markdown", buffer: Buffer.from("# Revenue\n\nAPAC revenue was $82M.") });
  await expect(page.getByRole("button", { name: /private-finance.md Ready/ })).toBeVisible({ timeout: 30000 });
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await page.getByLabel("Email address").fill("alice@example.test");
  await page.getByLabel("Password", { exact: true }).fill("test-workspace-password");
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page.getByRole("button", { name: "People & access", exact: true })).toHaveCount(0);
  await expect(page.locator(".document-row")).toHaveCount(0);
  await page.getByRole("textbox", { name: "Ask your documents" }).fill("Show APAC revenue as a chart");
  await page.getByRole("button", { name: "Send question" }).click();
  await expect(page.locator(".markdown")).toContainText("No authorized supporting passages");
  await expect(page.locator(".generative-chart")).toHaveCount(0);
  await page.locator(".security-trace summary").click();
  await expect(page.locator(".security-trace")).toContainText("0 / 0");
  await page.screenshot({ path: "../.scratch/zero-trust-denied.png" });
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await page.getByLabel("Email address").fill("admin@example.test");
  await page.getByLabel("Password", { exact: true }).fill("test-workspace-password");
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await page.getByRole("button", { name: /private-finance.md Ready/ }).click();
  await page.getByLabel("alice@example.test", { exact: true }).check();
  await page.getByRole("button", { name: "Save permissions" }).click();
  await expect(page.getByRole("status")).toContainText("Permissions saved");
  await page.getByRole("button", { name: "Close", exact: true }).click();
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await page.getByLabel("Email address").fill("alice@example.test");
  await page.getByLabel("Password", { exact: true }).fill("test-workspace-password");
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page.getByRole("button", { name: /private-finance.md Ready/ })).toBeVisible();
  await page.getByRole("textbox", { name: "Ask your documents" }).fill("Show APAC revenue as a chart");
  await page.getByRole("button", { name: "Send question" }).click();
  await expect(page.locator(".generative-chart")).toBeVisible();
  await expect(page.locator(".security-trace summary")).toContainText("1 authorized context chunks");
  await page.getByRole("button", { name: /Architecture/ }).click();
  await expect(page.getByRole("heading", { name: "Trust is a boundary. Not a prompt." })).toBeVisible();
  await page.getByRole("button", { name: /Verify identity/ }).click();
  await expect(page.locator(".architecture-detail")).toContainText("active session");
  await page.getByRole("button", { name: /Filter retrieval/ }).click();
  await page.screenshot({ path: "../.scratch/zero-trust-architecture.png", animations: "disabled" });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator(".architecture-canvas")).toBeVisible();
  await expect.poll(async () => page.locator(".sidebar").evaluate(el => el.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "../.scratch/zero-trust-mobile.png", animations: "disabled" });
  expect(errors).toEqual([]);
});
